swagger: "2.0"
info:
  version: "0.0.1"
  title: Hello World App
# during dev, should point to your local machine
host: localhost:3000
# basePath prefixes all resource paths 
basePath: /api/
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /user/logout:
    x-swagger-router-controller: user
    get:
      description: check login
      operationId: logout
      responses:
        "200":
          description: Success
        default:
          description: Error
      parameters:
      - name: token
        in: body
        schema:
          type: string
          example:
            'asdasdasdasdasdasd'
  /user/login:
    x-swagger-router-controller: user
    get:
      description: check login
      operationId: checkLogin
      responses:
        "200":
          description: Success
        default:
          description: Error
    post:
      description: login route
      # used as the method name of the controller
      operationId: login
      responses:
        "200":
          description: Success
        default:
          description: Error
      parameters:
      - name: creds
        in: body
        schema:
          type: string
          example:
            username: username
            password: password
  /user/create:
    x-swagger-router-controller: user
    post:
      description: check login
      operationId: newUser
      responses:
        "200":
          description: Success
        default:
          description: Error
      parameters:
      - name: userData
        in: body
        schema:
          type: string
          example:
            username: username
            password: password
            email: email
  /movies/all:
    # binds a127 app logic to a route
    x-swagger-router-controller: movies
    get:
      description: Returns all movies list to the caller
      # used as the method name of the controller
      operationId: all
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /movies/my_list:
    # binds a127 app logic to a route
    x-swagger-router-controller: movies
    get:
      description: Returns all movies list to the caller
      # used as the method name of the controller
      operationId: mine
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /movies/{movId}:
    # binds a127 app logic to a route
    x-swagger-router-controller: movies
    get:
      description: Loads single movie
      # used as the method name of the controller
      operationId: single
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      parameters:
      - name: movId
        in: path
        description: movie IDasd  as
        required: true
        type: integer
    put:
      description: Edits single movie
      # used as the method name of the controller
      operationId: edit
      responses:
        "200":
          description: Success
        default:
          description: Error
      parameters:
      - name: movId
        in: path
        description: movie ID
        required: true
        type: integer
      - name: props
        in: body
        required: true
        schema:
          type: object
          example:
            name: LOTR
            desc: Great one
            actors: {1,2,3}
  /movies/new:
    x-swagger-router-controller: movies
    post:
      description: Creates single movie entry
      # used as the method name of the controller
      operationId: create
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/ListResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
      parameters:
      - name: props
        in: body
        required: true
        schema:
          type: object
          example:
            name: LOTR
            desc: Great one
            actors: {1,2,3}
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  
  ListResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
